// Ask-the-Lease proxy — Phase 22C (citation MVP)
// Fetches stored extracted_text for a lease document, sends it to Claude
// with the user's question, and returns { answer, citations, fileUrl }.
// Citations include verbatim quote, section reference, and page number (when
// the stored text was generated by extractPdfText which adds "--- Page N ---" markers).

const _t = require('./_pilot-target');
// The prompt and the parser are one agreement; both sides of the tests use the
// same module so a passing suite cannot mean a different shipped prompt.
const { SYSTEM_PROMPT, parseStructuredResponse } = require('./_ask-lease-contract');
const SUPABASE_URL      = _t.url;
const SUPABASE_ANON_KEY = _t.anonKey;
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('[api/ask-lease] Supabase URL/anon not configured for ' + _t.name + ' target');
}

const _rl = new Map();
function _chkRate(uid, max, winMs) {
  const now = Date.now();
  let w = _rl.get(uid) || { n: 0, reset: now + winMs };
  if (now > w.reset) w = { n: 0, reset: now + winMs };
  w.n++; _rl.set(uid, w);
  return w.n <= max;
}

async function _verifyUser(req, res) {
  const tok = (req.headers['authorization'] || '').replace(/^Bearer\s+/, '');
  if (!tok) { res.status(401).json({ error: 'Authentication required' }); return null; }
  try {
    const r = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
      signal: AbortSignal.timeout(3000),
      headers: { apikey: (_t.serviceRoleKey || SUPABASE_ANON_KEY).trim(), Authorization: `Bearer ${tok}` },
    });
    if (!r.ok) { res.status(401).json({ error: 'Invalid or expired token' }); return null; }
    const user = await r.json();
    if (!user?.id) { res.status(401).json({ error: 'User identity missing' }); return null; }
    return user;
  } catch (e) {
    const timedOut = e?.name === 'TimeoutError' || e?.name === 'AbortError';
    res.status(timedOut ? 503 : 500).json({ error: timedOut ? 'Auth service unavailable — try again' : 'Auth check failed' });
    return null;
  }
}

const MAX_QUESTION_LEN  = 1000;   // chars
// 300k chars ≈ 75k tokens — fits a 50-page lease well within Claude's 200k-token window.
// Paired with MAX_PAGES=50 in extractPdfText: stored text for most leases stays under
// 250k chars, so this constant acts as a safety guard rather than an active truncation point.
const MAX_LEASE_TEXT    = 300000; // chars
const ANTHROPIC_TIMEOUT = 45000;  // ms — fail clearly before Vercel's 60s maxDuration

// Ask-the-Lease is pinned to Sonnet regardless of the CLAUDE_MODEL env var.
// The operator may set CLAUDE_MODEL=haiku for cheap bulk field extraction, but QA
// on nuanced lease language requires Sonnet-level reasoning.
const ASK_MODEL = 'claude-sonnet-4-6';

function sbKey() {
  return _t.serviceRoleKey || SUPABASE_ANON_KEY;
}

async function fetchLeaseDoc(leaseDocumentId) {
  const k   = sbKey();
  const url = `${SUPABASE_URL}/rest/v1/lease_documents?id=eq.${encodeURIComponent(leaseDocumentId)}&select=id,property_id,file_name,tenant_name,extracted_text,used_pdf_direct,file_url`;
  const res = await fetch(url, {
    headers: {
      'apikey':        k,
      'Authorization': `Bearer ${k}`,
    },
  });
  const text = await res.text();
  let rows;
  try { rows = JSON.parse(text); } catch { rows = []; }
  if (!Array.isArray(rows) || rows.length === 0) return null;
  return rows[0];
}

async function _ownsLeaseDoc(doc, userId) {
  if (!doc.property_id) return false;
  const k   = sbKey();
  const url = `${SUPABASE_URL}/rest/v1/properties?id=eq.${encodeURIComponent(doc.property_id)}&user_id=eq.${encodeURIComponent(userId)}&select=id`;
  const res = await fetch(url, { headers: { 'apikey': k, 'Authorization': `Bearer ${k}` } });
  const text = await res.text();
  let rows;
  try { rows = JSON.parse(text); } catch { rows = []; }
  return Array.isArray(rows) && rows.length > 0;
}

async function callClaude(leaseText, question) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY not configured on server');

  const system = SYSTEM_PROMPT;

  const truncated     = leaseText.length > MAX_LEASE_TEXT;
  const textToSend    = truncated ? leaseText.slice(0, MAX_LEASE_TEXT) : leaseText;
  const charsAnalyzed = textToSend.length;
  const userContent   = `LEASE TEXT:\n${textToSend}\n\nQUESTION: ${question}`;

  const controller = new AbortController();
  const timeoutId  = setTimeout(() => controller.abort(), ANTHROPIC_TIMEOUT);

  let resp;
  try {
    resp = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      signal: controller.signal,
      headers: {
        'Content-Type':      'application/json',
        'anthropic-version': '2023-06-01',
        'x-api-key':         apiKey,
      },
      body: JSON.stringify({
        model:      ASK_MODEL,
        max_tokens: 2048,
        system,
        messages: [{ role: 'user', content: userContent }],
      }),
    });
  } catch (err) {
    if (err.name === 'AbortError') throw new Error('Claude took too long to respond (>45s). Try a shorter question or try again.');
    throw err;
  } finally {
    clearTimeout(timeoutId);
  }

  if (!resp.ok) {
    const errText = await resp.text();
    throw new Error(`Anthropic API error ${resp.status}: ${errText.slice(0, 200)}`);
  }

  const json = await resp.json();
  const raw  = json?.content?.[0]?.text;
  if (!raw) throw new Error('No content returned from Claude');

  const { answered, answer, citations } = parseStructuredResponse(raw);

  return {
    answered,
    answer,
    citations,
    truncated,
    charsAnalyzed,
    model:        json.model,
    inputTokens:  json.usage?.input_tokens,
    outputTokens: json.usage?.output_tokens,
  };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const user = await _verifyUser(req, res);
  if (!user) return;
  if (!_chkRate(user.id, 15, 60000)) {
    return res.status(429).json({ error: 'Too many requests — please slow down.' });
  }

  const { leaseDocumentId, question } = req.body || {};

  if (!leaseDocumentId) {
    return res.status(400).json({ error: 'Missing leaseDocumentId' });
  }
  if (!question || !question.trim()) {
    return res.status(400).json({ error: 'Missing question' });
  }
  if (question.length > MAX_QUESTION_LEN) {
    return res.status(400).json({ error: `Question too long (max ${MAX_QUESTION_LEN} characters)` });
  }

  let doc;
  try {
    doc = await fetchLeaseDoc(leaseDocumentId);
  } catch (err) {
    console.error('[ask-lease] Supabase fetch failed:', err.message);
    return res.status(502).json({ error: 'Failed to fetch lease document' });
  }

  if (!doc) {
    return res.status(404).json({ error: 'Lease document not found' });
  }

  if (!await _ownsLeaseDoc(doc, user.id)) {
    return res.status(403).json({ error: 'Forbidden' });
  }

  if (!doc.extracted_text) {
    const reason = doc.used_pdf_direct
      ? 'This lease was processed via PDF vision — text was not stored. Re-upload the PDF to enable Ask the Lease.'
      : 'No extracted text is available for this lease document.';
    return res.status(422).json({ error: reason });
  }

  let result;
  try {
    result = await callClaude(doc.extracted_text, question.trim());
  } catch (err) {
    console.error('[ask-lease] Claude call failed:', err.message);
    return res.status(500).json({ error: err.message || 'Claude request failed' });
  }

  console.log(
    '[ask-lease] answered | doc:', leaseDocumentId,
    '| tenant:', doc.tenant_name,
    '| chars:', result.charsAnalyzed, result.truncated ? '(truncated)' : '(full)',
    '| answered:', result.answered, '| citations:', result.citations.length,
    '| in:', result.inputTokens, '| out:', result.outputTokens
  );

  return res.status(200).json({
    // answered:false means this lease cannot answer the question. The client
    // must render that as a refusal, not as an answer with no sources.
    answered:      result.answered,
    answer:        result.answer,
    citations:     result.citations,
    fileUrl:       doc.file_url || null,
    truncated:     result.truncated,
    charsAnalyzed: result.charsAnalyzed,
  });
}
